Create draft of README.md file
openfga/.github pull request #9
Opened 2022-10-31 19:21 UTC by matthewpereira

## Description
First draft of a 'README' for the community repo. Still need to add badges:

Badges
* Twitter
* Docs
* Discord
* CLO Monitor ([![CLOMonitor](https://img.shields.io/endpoint?url=https://clomonitor.io/api/projects/cncf/openfga/badge)](https://clomonitor.io/projects/cncf/openfga))

I'll update this draft PR as soon as I have those changes ready.

2022-11-01 13:54 UTC, aaguiarz reviewed
Can we add a link to https://github.com/openfga/community#community-projects in the 'Resources' section?

2022-11-03 21:05 UTC, aaguiarz requested changes
Added a few comments

2022-11-03 21:05 UTC, aaguiarz commented on profile/README.md
> +* **Discord**: Join the conversation on the [Auth0 Labs Discord](https://discord.gg/8naAwJfWN6), where FGA has channels specific for general chat, announcements about the product, support, feedback.
```suggestion
* **Discord**: Join the conversation on [Discord](https://discord.gg/8naAwJfWN6), where FGA has channels specific for general chat, announcements about the product, support, feedback.
```

Avoid mentioning Auth0

2022-11-03 21:05 UTC, aaguiarz commented on profile/README.md
> +In addition to code changes, we welcome feedback about the user experience and documentation experience, the product's architecture, new feature ideas, and other discussion ideas you might have. Visi
```suggestion
In addition to code changes, we welcome feedback about the user experience and documentation experience, the product's architecture, new feature ideas, and other discussion ideas you might have. Visit our [Github Discussions Board](https://github.com/orgs/openfga/discussions) or [Discord](https://discord.gg/8naAwJfWN6) and join the conversation!
```
Added whitespace

2022-11-03 21:05 UTC, aaguiarz commented on profile/README.md
> +OpenFGA was [donated to the Cloud Native Computing Foundation](https://www.cncf.io/projects/openfga/) on September 14, 2022, and is currently at the Sandbox level of graduation.
```suggestion
OpenFGA was originally developed by Auth0/Okta, and  [donated to the Cloud Native Computing Foundation](https://www.cncf.io/projects/openfga/) on September 14, 2022, and is currently at the Sandbox level of graduation.
```

2022-11-14 15:29 UTC, matthewpereira commented
Just waiting on EasyCLA to be approved and then we can merge.

2022-11-14 16:51 UTC, aaguiarz approved these changes
LGTM

2022-11-14 16:55 UTC, merged